# start/stop

start-instance:
    docker compose up --detach --wait postgresql

stop-instance:
    docker compose down

restart-instance:
    just stop-instance && just start-instance

remove-volume:
    docker volume rm sandbox_postgresql_data

# access

console:
    psql --dbname "$CONNECTION_STRING"

shell:
    docker exec --interactive --tty --user=root postgresql bash

storage:
    docker exec --interactive --tty --user=root --workdir=/var/lib/postgresql/data postgresql bash

# monitoring

logs:
    docker logs --follow postgresql

stats:
    docker stats
