# start/stop

start-instance:
    docker compose up --detach --wait postgresql

stop-instance:
    docker compose down

restart-instance:
    just stop-instance && just start-instance

remove-volume:
    just stop-instance && docker volume rm sandbox_postgresql_data

# access

console:
    psql --dbname "$CONNECTION_STRING"

shell:
    docker exec --interactive --tty --user=root postgresql bash

storage:
    docker exec --interactive --tty --user=root --workdir="/var/lib/postgresql/$POSTGRESQL_IMAGE_VERSION/docker" postgresql bash

wal:
    docker exec --interactive --tty --user=root --workdir="/usr/lib/postgresql/$POSTGRESQL_IMAGE_VERSION/bin" postgresql bash

# monitoring

logs:
    docker logs --follow postgresql

stats:
    docker stats

pgbench:
    time --format='Elapsed: %e seconds ' pgbench  --client=20 --transactions=10 --no-vacuum --connect --progress=5 --file=./queries/simple.sql

execute-query:
    time --format='Elapsed: %e seconds ' psql --dbname "$CONNECTION_STRING" --file=./queries/simple.sql;

terminate-backends:
    psql --dbname "$CONNECTION_STRING" --command="SELECT pg_cancel_backend(pid) FROM pg_stat_activity WHERE state = 'active' and pid <> pg_backend_pid()";

# setup

show-ide-connection:
    @echo "Postgresql server listening on host <localhost> on port <$POSTGRESQL_EXPOSED_PORT>"
    @echo "The open database name is <$POSTGRESQL_DATABASE_NAME>"
    @echo "Log in as user <$POSTGRESQL_USER_NAME>, password <$POSTGRESQL_USER_PASSWORD> "
    @echo "JDBC URL is <$CONNECTION_STRING_JDBC>"