setup:
    sudo chown microsoft-identity-broker postgresql.conf

create-dataset:
    curl --output dump.zip https://edu.postgrespro.com/demo-big-en.zip
    unzip dump.zip && rm dump.zip && mv demo-big-en-20170815.sql dump.sql
    psql --dbname "$CONNECTION_STRING" --file dump.sql
    psql --dbname "$CONNECTION_STRING" --command="DROP DATABASE IF EXISTS flight;"
    psql --dbname "$CONNECTION_STRING" --command="ALTER DATABASE demo RENAME TO flight;"
    rm dump.sql
    echo "You can connect using $CONNECTION_STRING_FLIGHT"

start:
    docker compose up --detach --wait postgresql

stop:
    docker compose down

restart:
    just stop
    just start

remove-volume:
    just stop && docker volume rm postgresql_data

console:
    psql --dbname "$CONNECTION_STRING_FLIGHT"

maintenance:
    psql --dbname "$CONNECTION_STRING_FLIGHT" --file=./queries/maintenance.sql

shell:
    docker exec -it $CONTAINER_NAME bash

logs:
    docker logs --follow $CONTAINER_NAME

pgactivity:
    pg_activity "$CONNECTION_STRING_FLIGHT"

pgbench:
    time --format='Elapsed: %e seconds ' pgbench --protocol=extended --connect --client=20 --jobs=4 --transactions=200 --no-vacuum --progress=5 --file=./queries/simple.sql

generate-activity:
    pgbench --client=10 --transactions=100 --no-vacuum --progress=5 --file=./queries/activity-flights.sql

running-queries:
    psql --dbname "$CONNECTION_STRING_FLIGHT" --file=./queries/running-queries.sql
